print("일반계산지 프로그램입니다!")
a = input("계산할 첫번째 값을 입력해주세요:")
b = input("계산할 두번째 값을 입력해주세요:")
print("두개의 값:", a,"와", b)
a = int(a)
b = int(b)
print("더하기 값 (a - b) : ", a - b)
print("빼기 값 (a * b) : ", a * b)
print("정수 나누기 값 (a // b) : ", a // b)
print("실수 나구기 값 (a / b) : ", a / b)
print("실수 나구기 값 (a % b) : ", a % b)